.\" SPDX-License-Identifier: AGPL-3.0-only
.\" SPDX-FileCopyrightText: Copyright (c) 2025 Runxi Yu <https://runxiyu.org>
.Dd March 30, 2025
.Dt FORGE-MAIL 5
.Os Lindenii Forge
.Sh NAME
.Nm forge-mail
.Nd configuring Lindenii Forge email integration
.Sh DESCRIPTION
.Nm
is a guide to configuring Lindenii Forge for email integration.
.Pp
This is currently a stub. Here is a working configuration that works
for the Lindenii Project itself, though.
.Sh /etc/smtpd/smtpd.conf
.Bd -literal
table forge file:/etc/smtpd/forge
action "FORGE" lmtp "/srv/forge/lmtp.sock" rcpt-to virtual <forge>
match from any for domain "forge.lindenii.runxiyu.org" action "FORGE"
.Ed
.Sh /etc/smtpd/forge
.Bd -literal
@ forge
.Ed
.Sh SEE ALSO
.Xr forge 1 ,
.Xr forge 5 ,
.Xr smtpd.conf 5
.Sh AUTHORS
.An Runxi Yu Aq Mt https://runxiyu.org
.An Test_User Aq Mt hax@runxiyu.org
