image: alpine/edge
secrets:
  - cf31947b-6d5d-4229-8ed3-56183102ea81
packages:
  - go
  - hut
  - golangci-lint
  - make
  - gcc
  - musl-dev
tasks:
  - prepare: |
      cd forge
      git checkout go
  - build: |
      cd forge
      make
  - lint: |
      cd forge
      golangci-lint run .
  - upload: |
      cd forge
      x="$(git describe --exact || true)"
      if [ -z "$x" ]; then
      	printf 'Not a tag, not uploading artifacts\n' >&2
      else
      	mv forge forge-"$x"-linux-amd64
      	hut git artifact -r forge upload forge-"$x"-linux-amd64
      fi
