image: alpine/edge
packages:
  - go
  - golangci-lint
  - make
  - gcc
  - musl-dev
tasks:
  - prepare: |
      cd forge
      git checkout go
  - build: |
      cd forge
      make
  - lint: |
      cd forge
      golangci-lint run .
