#!/bin/sh
#
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (c) 2025 Runxi Yu <https://runxiyu.org>

set -eu

if [ x"$(indent --version)" != x'FreeBSD indent 2.0' ]
then
	printf 'indent(1) version mismatch\n' >&2
	exit 1
fi

find . -name '*.c' -exec indent '{}' ';'
